#!/bin/bash

[ -n "$PS1" ] \
    && . ~/.bash_profile

function open_pyenv()
{
    export PATH="/home/rhding/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
}
export PATH="/home/rhding/ficus/.ficus/wrapper:$PATH"

